Dockerisation completed

diff --git a/front-end-nextjs/Dockerfile b/front-end-nextjs/Dockerfile
--- a/front-end-nextjs/Dockerfile
+++ b/front-end-nextjs/Dockerfile
@@ -1,15 +1,15 @@
-FROM node:18-alpine AS base
+FROM node:18-alpine
 
 WORKDIR /app
 
 COPY package.json yarn.lock* package-lock.json* ./
 
-RUN  \
-    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-    elif [ -f package-lock.json ]; then npm install; \
-    else echo "Error: Lockfile not found" && exit 1; \
-    fi
-
+# RUN  \
+#     if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+#     elif [ -f package-lock.json ]; then npm install; \
+#     else echo "Error: Lockfile not found" && exit 1; \
+#     fi
+RUN npm ci
 COPY . .
 
 RUN npm run build
