Added frontend docker build commands in workflow

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -16,15 +16,39 @@ jobs:
     steps:
     - name: Checkout
       uses: actions/checkout@v4
-    - name: Build Backend Image
-      run: docker build ./api/ -t adrashxprojects/qr_backend:latest
+    - name: Build Images
+      run: |
+        docker build ./api/ -t adrashxprojects/qr_backend:latest
+        if [ $? -eq 0 ]; then
+          echo "Backend Docker Image created successfully!!"
+        else
+          echo "Error building backend image"
+        fi
+
+        docker build ./front-end-nextjs/ -t adrashxprojects/qr_frontend:latest
+        if [ $? -eq 0 ]; then
+          echo "Frontend Docker Image created successfully!!"
+        else
+          echo "Error building frontend image"
+        fi
+        
     - name: Login to DockerHub
       run : |
         docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
         echo "Login completed !!"
+        
     - name: Push Backend Image To Repository
       run: |
         docker push adrashxprojects/qr_backend:latest
         if [ $? -eq 0 ]; then
-          echo "Docker Image Pushed Successfully"
+          echo "Backend Docker Image Pushed Successfully"
+        else
+          echo "Error pushing image !!!"
+        fi
+
+        docker push adrashxprojects/qr_frontend:latest
+        if [ $? -eq 0 ]; then
+          echo "Frontend Docker Image Pushed Successfully"
+        else
+          echo "Error pushing image !!!"
         fi
